### ISSUE TITLE
Scrollbars are disabled for outside of iFrame

### ISSUE THREAD

**Issue by lordtatty** [talis/aspire-moodle-integration#37]
We are currently disabling scroll for the whole-page here: https://github.com/talis/aspire-moodle-integration/blob/9ce4c44f3707d3ea1170c53fe5614519c90627bf/2.x-activity-module/mod/aspirelists/view.php#L135

This means that for templates with surrounding content, that content can disappear off the bottom of the viewable area and the user cannot scroll to it.  Recommend changing the value of this from 'hidden' to 'auto'.

**Comment by timhodson** [comment]
@lordtatty I agree with this approach. We should not be blocking users from access moodle content that is not the responsibility of this plugin.

**Comment by lordtatty** [comment]
The PR for this has now been merged.
