### ISSUE TITLE
Investigate change to patched line.

### ISSUE THREAD

**Issue by timhodson** [talis/aspire-moodle-integration#38]
Open LMS patched this line in the plugin in their December production release, we need to investigate why and whether this change will cause any issues.

```
lib.php
197: $cm->set_content($renderer->display_aspirelists($aspirelist));
becomes
197: $cm->set_content($renderer->display_aspirelists($aspirelist), true);
```

**Comment by lordtatty** [comment]
The "true" parameter being added tells the content manager ``$cm`` that this content has already been formatted, so it doesn't need formatting again.  Typically the content manager will try to format this using ``format_text()`` which lives here: https://github.com/moodle/moodle/blob/master/lib/weblib.php#L1218

However we are already formatting this in ``display_aspirelists()``.  https://github.com/talis/aspire-moodle-integration/blob/475fe3a868de0b19bd2ffe77392a6ff7ee23cd67/moodle-activity-module-lti-wrapper/mod/aspirelists/renderer.php 

Here we can see that most values being added to the output are controlled from the moodle side.  The only value that come from the user side is being passed through ``format_module_intro()``, which is formatting the string itself using the moodle internal tool ``format_text()`` which would ordinarily be used by the content manager if we did not pass the ``true`` value above.
