### ISSUE TITLE
Will there be a version for 2.9? pluginlib deprecated.

### ISSUE THREAD

**Issue by richheath** [talis/aspire-moodle-integration#6]
They have deprecated /lib/pluginlib.php in Moodle 2.9 (https://tracker.moodle.org/browse/MDL-46122), upon which this plugin relies. Therefore when trying to add a resource list it fails to a white screen or the following error with error reporting on (path replaced with ### for security):

Warning: require_once(/srv/www/vhosts/###/moodle/lib/pluginlib.php): failed to open stream: No such file or directory in /srv/www/vhosts/###/moodle/mod/aspirelists/mod_form.php on line 10 Fatal error: require_once(): Failed opening required '/srv/www/vhosts/####/moodle/lib/pluginlib.php' (include_path='/srv/www/vhosts/####/moodle/lib/zend:/srv/www/vhosts/###/moodle/lib/pear:.:/usr/share/php5:/usr/share/php5/PEAR') in /srv/www/vhosts/####/moodle/mod/aspirelists/mod_form.php on line 10

**Comment by timhodson** [comment]
This has long been resolved by moving to Moodle version 3 and above
